import type { Metadata } from "next";
import {  DM_Sans as FontSans,  } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import bg from '@/public/home-bg.png'
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const style={
  backgroundImage: `url(${bg.src})`,
  width: '100%',
  height: '100%',
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased home-bg text-white bg-black",
          fontSans.variable
        )} 
      >
        {children}
      </body>
    </html>
  );
}
